### ISSUE TITLE
Create the first interface of the application

### ISSUE THREAD

**Issue by sumanthst24** [sumanthst24/android-development#1]
You need to create an interface that appears first when the application opens

It should be the name of the application with a suitable background

**Comment by suprajaLara** [comment]
What should be included? 
Like, navigation bar, menu, any other options.
I can take this issue.

**Comment by sumanthst24** [comment]
No just the front end screen which says Algo_Expert with a relevant background

**Comment by sumanthst24** [comment]
I assigned you the task @suprajaLara 
You can start working on it
and make sure you make a pull request to team AD-04 branch only

**Comment by suprajaLara** [comment]
Here is the link to pull request -> #3 
Please check the link and update.
@sumanthst24

**Comment by sumanthst24** [comment]
have you used linear layout @suprajaLara ?

**Comment by sumanthst24** [comment]
Okay will check it

**Comment by sumanthst24** [comment]
use constraint layout

**Comment by suprajaLara** [comment]
modified to constraint layout. 
Here is the link to pull request -> #5 
Please check and updtate. @sumanthst24
